// web/app/automode/_components/DebugPanel.tsx
"use client";

import type { DebugEntry } from "../_types/types";

type DebugPanelModel = {
  debugOn: boolean;
  setDebugOn: (updater: boolean | ((prev: boolean) => boolean)) => void;

  debugExpanded: boolean;
  setDebugExpanded: (updater: boolean | ((prev: boolean) => boolean)) => void;

  debugEntries: DebugEntry[];
  setDebugEntries: (
    updater: DebugEntry[] | ((prev: DebugEntry[]) => DebugEntry[])
  ) => void;

  debugReqText: string;
  setDebugReqText: (v: string) => void;

  debugSchemaOld: any;
  setDebugSchemaOld: (v: any) => void;

  debugSchemaNew: any;
  setDebugSchemaNew: (v: any) => void;

  debugPromptText?: string;
  setDebugPromptText?: (v: string) => void;
};

type DebugPanelUI = {
  BTN_BASE: string;
  BTN_SM: string;
  BTN_XS: string;
  BTN_SECONDARY: string;
  BTN_OUTLINE: string;
};

type Props = {
  model: DebugPanelModel;
  ui: DebugPanelUI;
};

export default function DebugPanel(props: Props) {
  const { model, ui } = props;

  const {
    debugOn,
    setDebugOn,
    debugExpanded,
    setDebugExpanded,

    setDebugEntries,
    setDebugReqText,
    setDebugSchemaOld,
    setDebugSchemaNew,
    setDebugPromptText,

    debugReqText,
    debugSchemaOld,
    debugSchemaNew,
  } = model;

  const { BTN_BASE, BTN_SM, BTN_XS, BTN_SECONDARY, BTN_OUTLINE } = ui;

  return (
    <div className="w-full">
      {/* Right-side actions only */}
      <div className="flex items-center justify-end gap-2">
        <button
          type="button"
          onClick={() => setDebugOn((v) => !v)}
          className={`${BTN_BASE} ${BTN_SM} ${BTN_SECONDARY}`}
          title="Toggle debug capture (internal)"
        >
          Debug Capture: {debugOn ? "ON" : "OFF"}
        </button>

        <button
          type="button"
          onClick={() => setDebugExpanded((v) => !v)}
          className={`${BTN_BASE} ${BTN_SM} ${BTN_SECONDARY}`}
        >
          {debugExpanded ? "Hide Debug Panel" : "Show Debug Panel"}
        </button>
      </div>

      {debugExpanded && (
        <div className="mt-4 rounded-2xl border border-slate-200 bg-slate-50 p-4">
          <div className="flex items-center justify-between">
            <div className="text-sm font-semibold text-slate-800">Debug Panel</div>

            <button
              type="button"
              onClick={() => {
                setDebugEntries([]);
                setDebugReqText("");
                setDebugSchemaOld(null);
                setDebugSchemaNew(null);
                if (setDebugPromptText) setDebugPromptText("");
              }}
              className={`${BTN_BASE} ${BTN_XS} ${BTN_OUTLINE}`}
              title="Clear adjust debug outputs"
            >
              Clear
            </button>
          </div>

          {/* ✅ ONLY 3 columns */}
          <div className="mt-3 grid grid-cols-1 gap-3 lg:grid-cols-3">
            <div className="rounded-xl bg-white p-3 ring-1 ring-slate-200">
              <div className="text-xs font-semibold text-slate-700">
                requirements.txt (this adjust)
              </div>
              <div className="mt-1 text-[11px] text-slate-500">
                After clicking <span className="font-semibold">Adjust structure</span>, show the
                requirements used for this run.
              </div>
              <pre className="mt-2 max-h-56 overflow-auto whitespace-pre-wrap break-words text-xs text-slate-600">
                {debugReqText ? debugReqText : "— (no requirements captured yet) —"}
              </pre>
            </div>

            <div className="rounded-xl bg-white p-3 ring-1 ring-slate-200">
              <div className="text-xs font-semibold text-slate-700">Old Schema</div>
              <div className="mt-1 text-[11px] text-slate-500">
                If you uploaded a schema, this is exactly that file (authoritative baseline).
              </div>
              <pre className="mt-2 max-h-56 overflow-auto whitespace-pre-wrap break-words text-xs text-slate-600">
                {debugSchemaOld
                  ? JSON.stringify(debugSchemaOld, null, 2)
                  : "— (no old schema yet) —"}
              </pre>
            </div>

            <div className="rounded-xl bg-white p-3 ring-1 ring-slate-200">
              <div className="text-xs font-semibold text-slate-700">
                New Schema (after adjust)
              </div>
              <div className="mt-1 text-[11px] text-slate-500">
                The schema generated by this Adjust run (current / merged schema).
              </div>
              <pre className="mt-2 max-h-56 overflow-auto whitespace-pre-wrap break-words text-xs text-slate-600">
                {debugSchemaNew
                  ? JSON.stringify(debugSchemaNew, null, 2)
                  : "— (no new schema yet) —"}
              </pre>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
